# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spr < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/rohan-mehta/spr"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rohan-mehta/spr/releases/download/v0.15.0/spr_darwin_x86_64.tar.gz"
      sha256 "6fcfeae725b523bc55aa09d02353b0777010d985d30dca56fcce951f9864d20a"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rohan-mehta/spr/releases/download/v0.15.0/spr_darwin_arm64.tar.gz"
      sha256 "4d90ce72568407b48473a96785a37ac802adbf3e9875a8ed94c176eb6c06ba22"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rohan-mehta/spr/releases/download/v0.15.0/spr_linux_x86_64.tar.gz"
        sha256 "706bc9c05d6827a270212b6c9b09dd2c6eacf23c4767d7d8b2db52dfdd7a04ce"

        def install
          bin.install "git-spr"
          bin.install "git-amend"
          bin.install "spr_reword_helper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rohan-mehta/spr/releases/download/v0.15.0/spr_linux_arm64.tar.gz"
        sha256 "8e80bbadcd05637f99f7db80d2cac3df911ff26b40c089c5d38531718eacb6e0"

        def install
          bin.install "git-spr"
          bin.install "git-amend"
          bin.install "spr_reword_helper"
        end
      end
    end
  end
end
